### ISSUE TITLE
AttributeError: adapters when running isaw.policy after creating new site on clean buildout

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.theme#76]
After running clean buildout (see further below), checked http://127.0.0.1:8081/ and followed prompts to create a new site. After checking the check-box next to `isaw.policy` and submitting the form, the following traceback was delivered to the browser at the URL http://127.0.0.1:8081/@@plone-addsite:

```
Site Error

An error was encountered while publishing this resource.


Sorry, a site error occurred.
Traceback (innermost last):

Module ZPublisher.Publish, line 249, in publish_module_standard
Module ZPublisher.Publish, line 197, in publish
Module zope.event, line 31, in notify
Module zope.component.event, line 24, in dispatch
Module zope.component._api, line 136, in subscribers
Module zope.component.registry, line 321, in subscribers
AttributeError: adapters

Troubleshooting Suggestions

The URL may be incorrect.
The parameters passed to this resource may be incorrect.
A resource that this resource relies on may be encountering an error.
For more detailed information about the error, please refer to the error log.

If the error persists please contact the site maintainer. Thank you for your patience.
```

Process was being run in debug mode with `bin/client1 fg`. The following tracebacks were delivered at the command line (note that a lot of debug output was also delivered before the tracebacks; I will append that in a comment in case it is of use.

```
2015-08-04 16:53:57 ERROR Zope.SiteErrorLog 1438721637.480.9934829359 http://127.0.0.1:8081/@@plone-addsite
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.CMFPlone.browser.admin, line 208, in __call__
  Module Products.CMFPlone.factory, line 105, in addPloneSite
  Module Products.GenericSetup.tool, line 365, in runAllImportStepsFromProfile
   - __traceback_info__: profile-isaw.policy:default
  Module Products.GenericSetup.tool, line 1119, in _runImportStepsFromContext
  Module Products.GenericSetup.tool, line 1030, in _doRunImportStep
   - __traceback_info__: portlets
  Module plone.app.portlets.exportimport.portlets, line 762, in importPortlets
  Module Products.GenericSetup.utils, line 509, in _importBody
  Module plone.app.portlets.exportimport.portlets, line 284, in _importNode
  Module plone.app.portlets.exportimport.portlets, line 293, in _initProvider
  Module plone.app.portlets.exportimport.portlets, line 347, in _initPortlets
  Module plone.app.portlets.exportimport.portlets, line 516, in _initAssignmentNode
  Module plone.app.portlets.exportimport.portlets, line 121, in import_assignment
  Module plone.app.portlets.exportimport.portlets, line 146, in import_node
  Module plone.app.portlets.exportimport.portlets, line 167, in import_node_for_field
  Module plone.app.portlets.exportimport.portlets, line 182, in import_node_for_field
  Module plone.app.portlets.exportimport.portlets, line 240, in from_unicode
  Module zope.schema._field, line 373, in fromUnicode
  Module zope.schema._bootstrapfields, line 182, in validate
  Module zope.schema._field, line 389, in _validate
ConstraintNotSatisfied: Exhibition
2015-08-04 16:53:57 ERROR ZServerPublisher exception caught
Traceback (most recent call last):
  File "/Users/paregorios/Documents/files/I/isaw.web/eggs/Zope2-2.13.22-py2.7.egg/ZServer/PubCore/ZServerPublisher.py", line 31, in __init__
    response=b)
  File "/Users/paregorios/Documents/files/I/isaw.web/eggs/Zope2-2.13.22-py2.7.egg/ZPublisher/Publish.py", line 455, in publish_module
    environ, debug, request, response)
  File "/Users/paregorios/Documents/files/I/isaw.web/eggs/Zope2-2.13.22-py2.7.egg/ZPublisher/Publish.py", line 276, in publish_module_standard
    if request is not None: request.close()
  File "/Users/paregorios/Documents/files/I/isaw.web/eggs/Zope2-2.13.22-py2.7.egg/ZPublisher/BaseRequest.py", line 218, in close
    notify(EndRequestEvent(None, self))
  File "/Users/paregorios/Documents/files/I/isaw.web/eggs/zope.event-3.5.2-py2.7.egg/zope/event/__init__.py", line 31, in notify
    subscriber(event)
  File "/Users/paregorios/Documents/files/I/isaw.web/eggs/zope.component-3.9.5-py2.7.egg/zope/component/event.py", line 24, in dispatch
    zope.component.subscribers(event, None)
  File "/Users/paregorios/Documents/files/I/isaw.web/eggs/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 136, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/Users/paregorios/Documents/files/I/isaw.web/eggs/zope.component-3.9.5-py2.7.egg/zope/component/registry.py", line 321, in subscribers
    return self.adapters.subscribers(objects, provided)
AttributeError: adapters
```

This was a completely fresh buildout on OSX 10.9.5. All dependencies were previously updated via brew and [all instructions in the buildout](https://github.com/isawnyu/isaw.web/blob/master/README.txt) were followed verbatim.

**Comment by paregorios** [comment]
On second thought, the log is so huge I won't append it here. Let me know if a copy is needed.

**Comment by alecpm** [comment]
If you could clear the log.  Start the instance fresh and then compress and email it to us that would be helpful.

**Comment by paregorios** [comment]
I've just emailed console output. Are there any logs in var/log/ that you'd like to see?

**Comment by alecpm** [comment]
This should be fixed now.

**Comment by paregorios** [comment]
Confirmed. I did a complete clean buildout and then was able to create a plone site and apply the isaw.policy product without errors. I would like to find out what the next steps are to get something that looks like what we're supposed to have for the new theme, but that's a separate task. Closing this ticket.
